// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/cometbft/cometbft/abci/types"
)

// AppConnEthQuery is an autogenerated mock type for the AppConnEthQuery type
type AppConnEthQuery struct {
	mock.Mock
}

// Error provides a mock function with no fields
func (_m *AppConnEthQuery) Error() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EthQuerySync provides a mock function with given fields: ctx, query
func (_m *AppConnEthQuery) EthQuerySync(ctx context.Context, query *types.RequestEthQuery) (*types.ResponseEthQuery, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for EthQuerySync")
	}

	var r0 *types.ResponseEthQuery
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.RequestEthQuery) (*types.ResponseEthQuery, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *types.RequestEthQuery) *types.ResponseEthQuery); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ResponseEthQuery)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *types.RequestEthQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAppConnEthQuery creates a new instance of AppConnEthQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppConnEthQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppConnEthQuery {
	mock := &AppConnEthQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
